### ISSUE TITLE
Is this repo being maintained?

### ISSUE THREAD

**Issue by mohit10verma** [HewlettPackard/Atlas#28]
Hi,

I was trying to build & run this, but have hit many issues. Is this repository being maintained? 

For example, with llvm 8.0.0 I was not able to build compiler-plugin because of this [issue](https://lists.llvm.org/pipermail/llvm-dev/2019-February/130273.html). After I fixed that, I still am not able to build runtime. I am getting a seg fault when I use the new instrumentation pass built using the complier-plugin.

**Comment by ssinghal53** [comment]
@mohit10verma -- No this repository is no longer being maintained.
